pipeline {
    agent any
    tools{
        oc 'oc'
    }
    stages {
        stage('Fetching Git Repository') {
            steps {
                git url: GIT_URL, branch: BRANCH
            }
        }
        stage ('Create Configurations') {
            steps {
                script {
                    openshift.withCluster( CLUSTER_NAME ) {
                        openshift.withProject( PROJECT_NAME ){
                            sh "cd ReactApp"
                            def processedTemplate = openshift.process( "-f", "./pipeline/ui-template.yaml", "--param-file=./pipeline/ui.env", "-p", PROJECT_NAME)
                            def createResources = openshift.create( processedTemplate )
                            def replaceResources = openshift.create( processedTemplate )
                        }
                    }
                }
            }
        }
        stage ('UI-Build') {
            steps {
                script {
                    openshift.withCluster( CLUSTER_NAME ) {
                        openshift.withProject( PROJECT_NAME ){
                            def buildConfig = openshift.selector( 'buildconfig/' + BUILD_PREFIX + "-ui-build" )
                            buildConfig.startBuild()
                            buildConfig.logs('-f')
                        }
                    }
                }    
            }
        }
        stage ('UI-Runtime Build') {
            steps {
                script {
                    openshift.withCluster( CLUSTER_NAME ) {
                        openshift.withProject( PROJECT_NAME ){
                            def buildConfig = openshift.selector( 'buildconfig/' + BUILD_PREFIX + "-ui-runtime" )
                            buildConfig.startBuild()
                            buildConfig.logs('-f')
                        }
                    }
                }    
            }
        }
        stage ('Deploying UI-Runtime') {
            steps {
                script {
                    openshift.withCluster( CLUSTER_NAME ) {
                        openshift.withProject( PROJECT_NAME ){
                            def devConfig = openshift.selector( 'deploymentconfig/' + BUILD_PREFIX + "-ui-deploy" )
                            devConfig.rollout().latest()
                        }
                    }
                }    
            }
        }
    }
}
